version: "3.8"
services:
  front:
    build:
      context: ./
      dockerfile: Dockerfile-dev
    image: front
    volumes:
      - ./src:/run/app/front/src
      - ./public:/run/app/front/public
    ports:
      - 8080:3000