version: '3.8'
services:
  front:
    build:
      context: .
      target: dev
    image: front
    environment:
      PORT: 8080
    volumes:
      - ./src:/run/app/front/src
      - ./public:/run/app/front/public
    ports:
      - 8080:8080
    stdin_open: true
