version: '3.8'
services:
  front:
    build:
      context: .
      target: dev
    image: front
    volumes:
      - ./src:/run/app/front/src
      - ./public:/run/app/front/public
    ports:
      - 3000:3000
    stdin_open: true
