name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: 'gcr.io/cloud-builders/docker'
      run: docker build -t gcr.io/sandbox-271819/document-reader-front:$COMMIT_SHA .
    - name: 'gcr.io/cloud-builders/docker'
      run: docker push gcr.io/sandbox-271819/document-reader-front:$COMMIT_SHA
    - name: 'gcr.io/cloud-builders/gcloud'
      run: gcloud run deploy document-reader-front --image gcr.io/sandbox-271819/document-reader-front:$COMMIT_SHA --region uscentral1-a --platform managed
      
